version: '3.8'

services:
  zein-holistic-web:
    container_name: "zein-holistic-web"
    image: zein-holistic-web:1.0.0
    ports:
      - 8181:80
  zein-holistic-api:
    container_name: "zein-holistic-api"
    image: zein-holistic-api:1.0.0
    ports:
      - 8989:8080
    environment:
      DATABASE_USERNAME: ukieTux
      DATABASE_PASSWORD: sembaran6
      DATABASE_URL: jdbc:mysql://zein-holistic-mysql:3306/zeinholistic
  zein-holistic-mysql:
    container_name: 'zein-holistic-mysql'
    image: mysql:5.7.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "sembaran6"
      MYSQL_USER: "ukieTux"
      MYSQL_PASSWORD: "sembaran6"
      MYSQL_DATABASE: "zeinholistic"
      TZ: "Asia/Makassar"
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Docker/zeinholistic-mysql:/var/lib/mysql